<?php

namespace Joselfonseca\LaravelTactician\Tests\Generators;

use Illuminate\Support\Facades\Artisan;
use Joselfonseca\LaravelTactician\Tests\TestCase;

/**
 * Class TestGenerators
 * @package Joselfonseca\LaravelTactician\Tests\Generators
 */
class TestGenerators extends TestCase {

    private $expectedCommandFile = __DIR__.'/../../vendor/orchestra/testbench/fixture/app/CommandBus/Commands/FooCommand.php';
    private $expectedHandlerFile = __DIR__.'/../../vendor/orchestra/testbench/fixture/app/CommandBus/Handlers/FooHandler.php';

    /**
     * Setup the test environment.
     *
     * @return void
     */
    public function setUp()
    {
        $this->clearTempFiles();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * Clean up the testing environment before the next test.
     *
     * @return void
     */
    public function tearDown()
    {
        $this->clearTempFiles();
        parent::tearDown();
    }

    /**
     * Clear the files that tests generated
     */
    protected function clearTempFiles()
    {
        if (file_exists($this->expectedCommandFile)) {
            unlink($this->expectedCommandFile);
        }

        if (file_exists($this->expectedHandlerFile)) {
            unlink($this->expectedHandlerFile);
        }
    }

    /**
     * Generate Command using Artisan
     */
    protected function makeCommand() {
        Artisan::call('make:tactician:command', ['name' => 'Foo']);
    }

    /**
     * Generate Handler using Artisan
     */
    protected function makeHandler() {
        Artisan::call('make:tactician:handler', ['name' => 'Foo']);
    }

    /**
     * Test Command file is created
     */
    public function test_it_creates_command()
    {
        $this->makeCommand();

        $this->assertTrue(file_exists($this->expectedCommandFile));
    }

    /**
     * Test DummyClass is replaced correctly in Command
     */
    public function test_it_names_command()
    {
        $this->makeCommand();

        $this->assertTrue(strpos(file_get_contents($this->expectedCommandFile), 'Class FooCommand') !== false);
        $this->assertTrue(strpos(file_get_contents($this->expectedCommandFile), 'class FooCommand') !== false);
        $this->assertTrue(strpos(file_get_contents($this->expectedCommandFile), 'FooCommand constructor') !== false);
    }

    /**
     * Test DummyNamespace is replaced correctly in Command
     */
    public function test_it_namespaces_command()
    {
        $this->makeCommand();

        $this->assertTrue(strpos(file_get_contents($this->expectedCommandFile), 'namespace App\CommandBus\Commands;') !== false);
    }

    /**
     * Test Handler file is created
     */
    public function test_it_creates_handler()
    {
        $this->makeHandler();

        $this->assertTrue(file_exists($this->expectedHandlerFile));
    }

    /**
     * Test DummyClass is replaced correctly in Handler
     */
    public function test_it_names_handler()
    {
        $this->makeHandler();

        $this->assertTrue(strpos(file_get_contents($this->expectedHandlerFile), 'Class FooHandler') !== false);
        $this->assertTrue(strpos(file_get_contents($this->expectedHandlerFile), 'class FooHandler') !== false);
        $this->assertTrue(strpos(file_get_contents($this->expectedHandlerFile), 'FooHandler constructor') !== false);
    }

    /**
     * Test DummyNamespace is replaced correctly in Handler
     */
    public function test_it_namespaces_handler()
    {
        $this->makeHandler();

        $this->assertTrue(strpos(file_get_contents($this->expectedHandlerFile), 'namespace App\CommandBus\Handlers;') !== false);
    }

    /**
     * Test instance of Command is injected to Handler
     */
    public function test_it_adds_handler_to_command()
    {
        $this->makeHandler();

        $this->assertTrue(strpos(file_get_contents($this->expectedHandlerFile), '* @param FooCommand $command') !== false);
        $this->assertTrue(strpos(file_get_contents($this->expectedHandlerFile), 'public function handle(FooCommand $command)') !== false);
    }

}